### ISSUE TITLE
Audit

### ISSUE THREAD

**Issue by Lomet** [The-Poolz/VaultManager#25]
`Where any user can provide any address as `from` which has already approved the
vaultManager.`

[poolz finance issue.pdf](https://github.com/The-Poolz/VaultManager/files/11968245/poolz.finance.issue.pdf)

**Comment by Lomet** [comment]
the implementation of
`IERC20(_tokenAddress).transferFrom(msg.sender, vaultAddress, _amount);`
will not work, the msg.sender is `isPermitted` - the hosting contract

**Comment by Lomet** [comment]
in our case, the full flow is :
user -> provider -> LDnft-> Vault

we can add `tx.origin == from`

**Comment by YouStillAlive** [comment]
`tx.origin` is not safe.

![image](https://github.com/The-Poolz/VaultManager/assets/68740472/7c0f0773-17cc-4f6d-ac37-a8b349103780)

**Comment by Lomet** [comment]
we can solve it with documentation? state that the using contract must pass only the msg.sender
any solution that we add, the controlling contract can override:
making the interface abstract with the implementation, but we need to do the same on the provider

**Comment by ashwinarora** [comment]
It is the responsibility of the `permittedAddress` to make sure deposits and withdrawals happen in a secure manner. The only purpose of Vault is to help the `permittedAddress`  to manage funds. Hence we should add a restriction in the `setPermitted` function to check that the `_address` is a contract and not an EOA.  Good documentation will also help here.

**Comment by Lomet** [comment]
how about some thing like this:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "./IVaultManager.sol";
import "./VaultManagerEvents.sol";
import "../Vault/Vault.sol";
import "poolz-helper-v2/contracts/GovManager.sol";
import "poolz-helper-v2/contracts/Array.sol";
import "@openzeppelin/contracts/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

contract VaultManager is IVaultManager, VaultManagerEvents, GovManager {
    using ECDSA for bytes32;

    //... your existing code here ...

    mapping(address => uint) public nonces;

    //... your existing code here ...

    function depositByToken(address _tokenAddress, address from, uint _amount, uint _nonce, bytes memory _signature)
        external
        override
        isPermitted
        isDepositActive(getCurrentVaultIdByToken(_tokenAddress))
        returns(uint vaultId)
    {
        // Verify the signature
        bytes32 message = prefixed(keccak256(abi.encodePacked(_tokenAddress, from, _amount, _nonce, address(this))));
        address signer = message.recover(_signature);
        require(signer != address(0) && signer == from, "Invalid signature");
        require(_nonce == nonces[from]++, "Invalid nonce");

        vaultId = getCurrentVaultIdByToken(_tokenAddress);
        address vaultAddress = vaultIdToVault[vaultId];
        assert(_tokenAddress == Vault(vaultAddress).tokenAddress());
        IERC20(_tokenAddress).transferFrom(from, vaultAddress, _amount);
        emit Deposited(vaultId, _tokenAddress, from, _amount);
    }

    //... your existing code here ...

    function prefixed(bytes32 hash) internal pure returns (bytes32) {
        return keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", hash));
    }
}
```
